if game.GameId == 7326934954 then
  loadstring(game:HttpGet("https://api.luarmor.net/files/v4/loaders/a7e252611b0eb6d248a7677e207bb296.lua"))()
elseif game.GameId == 7709344486 then
  loadstring(game:HttpGet("https://api.luarmor.net/files/v4/loaders/2cca9c39a03ca533bd36385871941903.lua"))()
elseif game.GameId == 7750955984 then
  loadstring(game:HttpGet("https://api.luarmor.net/files/v4/loaders/214851b923c77022e74c1c893f38605a.lua"))()
elseif game.GameId == 7851663243 then
  loadstring(game:HttpGet("https://api.luarmor.net/files/v4/loaders/ee03c7c2ca74359f16eac5bfd15157de.lua"))()
elseif game.GameId == 7018190066 then
loadstring(game:HttpGet("https://api.luarmor.net/files/v4/loaders/d1b5425eaee3f03fccfc3c0a49f395e6.lua"))()
elseif game.GameId == 7939389895 then
 loadstring(game:HttpGet("https://api.luarmor.net/files/v4/loaders/343bed709ce2f02045050cc5d2bf3864.lua"))()
else
 game.Players.LocalPlayer:Kick("[Aura Hub]: Load Failed - Script Not Support")
end
